//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _72 {
            get {
                object obj = ResourceManager.GetObject("_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;PITNOW1.WAV In. In. In.&lt;
        ///&gt;PITNOW2.WAV Coming in.&lt;
        ///&gt;EASEOFF1.WAV Off. Off. Off.&lt;
        ///&gt;EASEOFF2.WAV Pulling back.&lt;
        ///&gt;FLYLAP1.WAV Push. Push. Push.&lt;
        ///&gt;FLYLAP2.WAV OK. OK. OK.&lt;
        ///&gt;OVERTAK1.WAV Pass. Pass. Pass.&lt;
        ///&gt;OVERTAK2.WAV Understood.&lt;
        ///&gt;BLOCK1.WAV Hold. Hold. Hold.&lt;
        ///&gt;BLOCK2.WAV Received.&lt;
        ///&gt;LEAVPIT1.WAV Out. Out. Out.&lt;
        ///&gt;LEAVPIT2.WAV Going out.&lt;
        ///&gt;12LAPS.WAV Coming in.&lt;
        ///&gt;ENGPOW.WAV Losing power.&lt;
        ///&gt;ENGHEA.WAV Overheating.&lt;
        ///&gt;ENGUND.WAV Losing traction.&lt;
        ///&gt;ENGVIB.WAV Rear wing breaking.&lt;
        ///&gt;FUEL.WAV Fuel lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMME_Enhanced {
            get {
                return ResourceManager.GetString("COMME_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;PITNOW1.WAV In. In. In.&lt;
        ///&gt;PITNOW2.WAV Coming in.&lt;
        ///&gt;EASEOFF1.WAV Off. Off. Off.&lt;
        ///&gt;EASEOFF2.WAV Pulling back.&lt;
        ///&gt;FLYLAP1.WAV Push. Push. Push.&lt;
        ///&gt;FLYLAP2.WAV OK. OK. OK.&lt;
        ///&gt;OVERTAK1.WAV Pass. Pass. Pass.&lt;
        ///&gt;OVERTAK2.WAV Understood.&lt;
        ///&gt;BLOCK1.WAV Hold. Hold. Hold.&lt;
        ///&gt;BLOCK2.WAV Received.&lt;
        ///&gt;LEAVPIT1.WAV Out. Out. Out.&lt;
        ///&gt;LEAVPIT2.WAV Going out.&lt;
        ///&gt;12LAPS.WAV Coming in.&lt;
        ///&gt;ENGPOW.WAV Losing power.&lt;
        ///&gt;ENGHEA.WAV Overheating.&lt;
        ///&gt;ENGUND.WAV Losing traction.&lt;
        ///&gt;ENGVIB.WAV Rear wing breaking.&lt;
        ///&gt;FUEL.WAV Fuel lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMME_Modified {
            get {
                return ResourceManager.GetString("COMME_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;PITNOW1.WAV In. In. In.&lt;
        ///&gt;PITNOW2.WAV Coming in.&lt;
        ///&gt;EASEOFF1.WAV Off. Off. Off.&lt;
        ///&gt;EASEOFF2.WAV Pulling back.&lt;
        ///&gt;FLYLAP1.WAV Push. Push. Push.&lt;
        ///&gt;FLYLAP2.WAV OK. OK. OK.&lt;
        ///&gt;OVERTAK1.WAV Pass. Pass. Pass.&lt;
        ///&gt;OVERTAK2.WAV Understood.&lt;
        ///&gt;BLOCK1.WAV Hold. Hold. Hold.&lt;
        ///&gt;BLOCK2.WAV Received.&lt;
        ///&gt;LEAVPIT1.WAV Out. Out. Out.&lt;
        ///&gt;LEAVPIT2.WAV Going out.&lt;
        ///&gt;12LAPS.WAV Coming in.&lt;
        ///&gt;ENGPOW.WAV Losing power.&lt;
        ///&gt;ENGHEA.WAV Overheating.&lt;
        ///&gt;ENGUND.WAV Losing traction.&lt;
        ///&gt;ENGVIB.WAV Rear wing breaking.&lt;
        ///&gt;FUEL.WAV Fuel lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COMME_Modified_Teams {
            get {
                return ResourceManager.GetString("COMME_Modified_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NAMEOUT {
            get {
                return ResourceManager.GetStream("NAMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NAMEP1 {
            get {
                return ResourceManager.GetStream("NAMEP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NAMEP2 {
            get {
                return ResourceManager.GetStream("NAMEP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NAMEP3 {
            get {
                return ResourceManager.GetStream("NAMEP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NAMEPIT {
            get {
                return ResourceManager.GetStream("NAMEPIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream P1C {
            get {
                return ResourceManager.GetStream("P1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream P2A {
            get {
                return ResourceManager.GetStream("P2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream P3A {
            get {
                return ResourceManager.GetStream("P3A", resourceCulture);
            }
        }
    }
}
